# Generated by Django 4.1.5 on 2023-01-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadata',
            options={'verbose_name': 'ПОИСК ПО АДРЕСУ', 'verbose_name_plural': 'ПОИСК ПО АДРЕСУ'},
        ),
    ]
